### ISSUE TITLE
"error": "Data not found"

### ISSUE THREAD

**Issue by maIwina** [SilasRodrigues19/LOL-WINRATE#3]

**Comment by SilasRodrigues19** [comment]
You probably didn't enter the environment variables:

```env
  RIOT_API="RGAPI-xxxxxxxxxxxxxxxxxxxxxxxxxx"
  SUMMONER_NAME="YoDa"
  REGION_CODE="BR1"
```

Remembering that in the variable `RIOT API` you must enter the value of your API that is generated when accessing the address below logged in with your account:

https://developer.riotgames.com/

![image](https://github.com/SilasRodrigues19/LOL-WINRATE/assets/47532703/480b7d51-f823-4f02-955d-f2642c796bf2)
